---
title: "linear_model"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(readr)
library(matrixStats)
library(reshape2)
```


```{r}
#### extracting likely variables 

#### DV: Blood Pressure 
#### calculating mean 
bloodpressure.XPT$dia_mean <- rowMeans(bloodpressure.XPT[,c("bpxdi1","bpxdi2","bpxdi3")])
bloodpressure.XPT$sys_mean <- rowMeans(bloodpressure.XPT[,c("bpxsy1","bpxsy2","bpxsy3")])

dv_bp <- bloodpressure.XPT %>% select(seqn,dia_mean,sys_mean,bpxsy1,bpxsy2,bpxsy3,bpxdi1,bpxdi2,bpxdi3)

#### IV: BMI Info 
bmi_variables <- body_measure.XPT %>% select(seqn,bmxarmc, bmxarml, bmxleg, bmxrecum, bmxsad1, bmxht, bmxwaist, bmxwt, bmxbmi)

#### IV: Demographic 
demo_variables <- demographic.XPT %>% select(seqn,riagendr, ridageyr)

#### IV: Diabetes 
dia_variables <- diabetes.XPT %>% select(seqn,diq010)

#### IV: Cholesteral 
high_chol_variables <- high_cholesterol.XPT %>% select(seqn,lbdhdd)
low_chol_variables <- low_cholesterol.XPT %>% select(seqn,lbdldl)
total_chol_variables <- cholesterol.XPT %>% select(seqn,lbxtc)


#### IV: Smoking 
smoking_variables <- cigs.XPT %>% select(seqn,smq040)
### recode: 
smoking_variables$smoker <- smoking_variables$smq040
smoking_variables$smq040 <- NULL 
smoking_variables <- smoking_variables %>% mutate(smoker = ifelse(smoker < 3,1,0))



####IV: glucose 
glu_variables <- glucose.XPT %>% select(seqn,lbxglu)

####merge 
lin_frame <- dv_bp 
variables <- c("bmi_variables","demo_variables","dia_variables","high_chol_variables","low_chol_variables","total_chol_variables","glu_variables")
for(i in 1:length(variables))
{
  lin_frame <- merge(lin_frame,eval(as.name(variables[i])),by=c("seqn"))
}
summary(lin_frame)
```

```{r}
####Prediction Frame 
lin_frame$bmxrecum <- NULL 
lin_frame_clean <- subset(lin_frame, select=-c(seqn,bpxsy1,bpxsy2,bpxsy3,bpxdi1,bpxdi2,bpxdi3)) 
lin_frame_clean <- na.omit(lin_frame_clean)
summary(lin_frame_clean)

#### Blood Pressure Frame 
lin_frame_bp <- na.omit(lin_frame)
summary(lin_frame_bp)
```


```{r}
####variable inspection 
cor(lin_frame_clean)
```


```{r}
#### Systolic prediction 
#### correlation
sys_lin <- subset(lin_frame_clean, select=-c(dia_mean))
cor(sys_lin)
#### model 1: linear regression

bpsys_linear1 = lm(sys_mean~.,sys_lin)
summary(bpsys_linear1)

  #### residual assumption 
  hist(bpsys_linear1$residuals)
  plot(bpsys_linear1$fitted.values,bpsys_linear1$residuals)

#### model 2: linear regression

bpsys_linear2 = lm(sys_mean~bmxarml + bmxsad1 + bmxwaist + riagendr + ridageyr + lbdldl + lbxtc + lbxglu,sys_lin)
summary(bpsys_linear2)

  #### residual assumption 
  hist(bpsys_linear2$residuals)
  plot(bpsys_linear2$fitted.values,bpsys_linear2$residuals)



#### prediction 
sys_predictions = predict(bpsys_linear2, newdata = lin_frame_clean)
summary(sys_predictions)
summary(lin_frame_clean$sys_mean)

### MSE data frame 
mse <- data.frame(predict_sys_mse = (lin_frame_clean$sys_mean - sys_predictions)^2, predicted_sys = sys_predictions,true_sys = lin_frame_bp$sys_mean, first_sys = lin_frame_bp$bpxsy1, first_sys_mse = (lin_frame_clean$sys_mean - lin_frame_bp$bpxsy1)^2 ) 

```

```{r}
#### Diastolic prediction 
#### correlation
dia_lin <- subset(lin_frame_clean, select=-c(sys_mean))
cor(dia_lin)

#### model 1: linear regression

bpdia_linear1 = lm(dia_mean~.,dia_lin)
summary(bpdia_linear1)

  #### residual assumption 
  hist(bpdia_linear1$residuals)
  plot(bpdia_linear1$fitted.values,bpdia_linear1$residuals)

  
#### model 2: linear regression
bpdia_linear2 = lm(dia_mean~bmxarmc + bmxht + diq010 + lbdldl + lbxtc,dia_lin)
summary(bpdia_linear2)

  #### residual assumption 
  hist(bpdia_linear2$residuals)
  plot(bpdia_linear2$fitted.values,bpdia_linear2$residuals)

  
#### model 3 with sys: linear regression
bpdia_linear3 = lm(dia_mean~.,lin_frame_clean)
summary(bpdia_linear1)

  #### residual assumption 
  hist(bpdia_linear3$residuals)
  plot(bpdia_linear3$fitted.values,bpdia_linear1$residuals)
  
#### model 4 with sys: linear regression
bpdia_linear4 = lm(dia_mean~sys_mean + bmxarmc + bmxarml + bmxht + riagendr + ridageyr + lbxtc,lin_frame_clean)
summary(bpdia_linear4)

  #### residual assumption 
  hist(bpdia_linear4$residuals)
  plot(bpdia_linear4$fitted.values,bpdia_linear1$residuals)


#### prediction 
dia_predictions = predict(bpdia_linear2, newdata = lin_frame_clean)
summary(dia_predictions)
summary(lin_frame_clean$dia_mean)

#### MSE Frame update
mse$predict_dia_mse <- (lin_frame_clean$dia_mean - dia_predictions)^2
mse$predicted_dia  <- dia_predictions
mse$true_dia <- lin_frame_bp$dia_mean
mse$first_dia <- lin_frame_bp$bpxdi1
mse$first_dia_mse <- (lin_frame_clean$sys_mean - lin_frame_bp$bpxdi1)^2

```



```{r}
### Density frame and plot for dia 
  ### Frame Creation 
  density_dia <- mse %>% select(predicted_dia,true_dia,first_dia)
  density_dia <- melt(density_dia)
  
  ### Plot 
  ggplot(density_dia, aes(x=value, fill=variable)) +
    geom_density(alpha=0.4)
  
  
### MSE frame and plot for dia
  bar_dia <- mse %>% select(first_dia_mse, predict_dia_mse) %>% summarise(first_dia_mse = sum(first_dia_mse), predict_dia_mse = sum(predict_dia_mse))
  bar_dia <- melt(bar_dia)
  
  ggplot(bar_dia, aes(x=variable, y=value, fill = variable)) +
  geom_bar(stat="identity") + theme_minimal()
  
  ###Scatter plot 
```
```{r}
### Density frame and plot for sys
  ### Frame Creation 
  density_sys <- mse %>% select(predicted_sys,true_sys,first_sys)
  density_sys <- melt(density_sys)
  
  ### Plot 
  ggplot(density_sys, aes(x=value, fill=variable)) +
    geom_density(alpha=0.4)

### MSE frame and plot for sys 
  bar_sys <- mse %>% select(first_sys_mse, predict_sys_mse) %>% summarise(first_sys_mse = mean(first_sys_mse), predict_sys_mse = mean(predict_sys_mse))
  bar_sys <- melt(bar_sys)
  
  ggplot(bar_sys, aes(x=variable, y=value, fill = variable)) +
  geom_bar(stat="identity") + theme_minimal()

  
  
### NEED TO THROW OUT DIASTOLIC OBSERVATION 
### CHECK FOR OUTLIERS AFTER CORRECTION 
### SCATTER PLOT FIRST vs. TRUE 
### DIASTOLIC HAS A QUADRATIC TREND WITH AGE 
### PREDICITNG BLOOD PRESSURE TRAJECTORY USING CLUSTERING 
mse$second_sys <- lin_frame_bp$bpxsy2
  ggplot(mse, aes(first_sys,predicted_sys))+
    geom_point()+
    const

```

