---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(caret) 
library(ggplot2)
library(dplyr)
library(readr)
library(Hmisc)
library(ggfortify)
#### Setting working directory 
knitr::opts_knit$set(root.dir = normalizePath("C:/Users/buehl/Documents/classes/senior-research"))
```



```{r}
#reading in all .XPT SAS files from NHANES_DATA folder 
nhanes_file_names <- list.files(path = "NHANES_DATA")
for(i in 1:length(nhanes_file_names))
{
  assign(paste(nhanes_file_names[i]), sasxport.get(paste0("NHANES_DATA/", nhanes_file_names[i])))
}
```

```{r}
years <- c("_1999.XPT","_2003.XPT","_2005.XPT","_2007.XPT","_2009.XPT","_2011.XPT","_2013.XPT","_2015.XPT")

####Blood Pressure 
bloodpressure <- bloodpressure_1999.XPT
for(i in 2:length(years))
{
  bloodpressure <- bind_rows(bloodpressure,get(paste0("bloodpressure",years[i])))    
}

####Bad Cholesterol
bad_cholesterol <- bad_cholesterol_1999.XPT
for(i in 2:length(years))
{
  bad_cholesterol <- bind_rows(bad_cholesterol,get(paste0("bad_cholesterol",years[i])))    
}

####body measure 
body_measure <- body_measure_1999.XPT
for(i in 2:length(years))
{
  body_measure <- bind_rows(body_measure,get(paste0("body_measure",years[i])))    
}

####demographic 
demographic <- demographic_1999.XPT
for(i in 2:length(years))
{
  demographic <- bind_rows(demographic,get(paste0("demographic",years[i])))    
}


####diabetes 
diabetes <- diabetes_1999.XPT
for(i in 2:length(years))
{
  diabetes <- bind_rows(diabetes,get(paste0("diabetes",years[i])))    
}


####glucose 
glucose <- glucose_1999.XPT
for(i in 2:length(years))
{
  glucose <- bind_rows(glucose,get(paste0("glucose",years[i])))    
}


####heart_health 
heart_health <- heart_health_1999.XPT
for(i in 2:length(years))
{
  heart_health <- bind_rows(heart_health,get(paste0("heart_health",years[i])))    
}


####kidney_health 
kidney_health <- kidney_health_1999.XPT
for(i in 2:length(years))
{
  kidney_health <- bind_rows(kidney_health,get(paste0("kidney_health",years[i])))    
}

####diabetes 
diabetes <- diabetes_1999.XPT
for(i in 2:length(years))
{
  diabetes <- bind_rows(diabetes,get(paste0("diabetes",years[i])))    
}


####hypertension
hypertension <- hypertension_1999.XPT
for(i in 2:length(years))
{
  hypertension <- bind_rows(hypertension,get(paste0("hypertension",years[i])))    
}

####smoking
smoking <- smoking_1999.XPT
for(i in 2:length(years))
{
  smoking <- bind_rows(smoking,get(paste0("smoking",years[i])))    
}

####total and good cholesterol 
cholesterol <- merge(get(paste0("cholesterol",years[3])),get(paste0("good_cholesterol",years[3])))
for(i in 4:length(years))
{
  
  a <- merge(get(paste0("cholesterol",years[i])),get(paste0("good_cholesterol",years[i])))
  cholesterol <- bind_rows(cholesterol,a)
}
total_good_cholesterol_1999.XPT
cholesterol <- bind_rows(cholesterol, total_good_cholesterol_1999.XPT)
cholesterol <- bind_rows(cholesterol, total_good_cholesterol_2001.XPT)
cholesterol <- bind_rows(cholesterol, total_good_cholesterol_2003.XPT)
```

```{r}
#### extracting likely variables 

#### DV: Blood Pressure 
  ### selecting blood relevant blood pressures 
  dv_bp <- bloodpressure %>% select(seqn,bpxsy1,bpxsy2,bpxsy3,bpxdi1,bpxdi2,bpxdi3)

  ### throwing out outliers
  dv_bp <- dv_bp %>% filter(bpxsy1 != 0 & bpxsy2 != 0 & bpxsy3 != 0 & bpxdi1 != 0 & bpxdi2 != 0 & bpxdi3 != 0 & bpxsy1 < 200 & bpxsy2 < 200 & bpxsy3 < 200 & bpxdi1 < 200 & bpxdi2,bpxdi3 < 200 & bpxdi1 > 27 & bpxdi2 > 27 & bpxdi3 > 27)
  summary(dv_bp)
  
  #### calculating mean 
  dv_bp$dia_mean <- rowMeans(dv_bp[,c("bpxdi1","bpxdi2","bpxdi3")])
  dv_bp$sys_mean <- rowMeans(dv_bp[,c("bpxsy1","bpxsy2","bpxsy3")])

#### IV: BMI Info 
bmi_variables <- body_measure %>% select(seqn,bmxarmc, bmxarml, bmxleg, bmxrecum, bmxsad1, bmxht, bmxwaist, bmxwt, bmxbmi)

#### IV: Demographic 
demo_variables <- demographic %>% select(seqn,riagendr, ridageyr,ridreth3)

demo_variables$ridreth3 <- ifelse(demo_variables$ridreth3 <= 2, 1,ifelse(demo_variables$ridreth3 == 3,2,ifelse(demo_variables$ridreth3 == 4,3, ifelse(demo_variables$ridreth3 == 6, 4, ifelse(demo_variables$ridreth3 == 7,5,NA)))))

#### dumming out 
  #### race
  demo_variables <- demo_variables %>% mutate(hispanic = ifelse(ridreth3 == 1,1,0),white = ifelse(ridreth3 == 2,1,0),black = ifelse(ridreth3 == 3,1,0),asian = ifelse(ridreth3 == 4,1,0),mult = ifelse(ridreth3 == 5,1,0))
  
  #### gender 
  demo_variables$riagendr[demo_variables$riagendr == 2] <- 0  

#### IV: Diabetes 
dia_variables <- diabetes %>% select(seqn,diq010) %>% filter(diq010 <= 3)
summary(dia_variables)
dia_variables$diq010[dia_variables$diq010 == 3] <- 1  
dia_variables$diq010[dia_variables$diq010 == 1] <- 1
dia_variables$diq010[dia_variables$diq010 == 2] <- 0

#### IV: Cholesteral 
chol_variables <- cholesterol %>% select(seqn,lbdhdd,lbxtc)
bad_chol_variables <- bad_cholesterol %>% select(seqn,lbdldl)

#### IV: Smoking 
  #### only yes and nos 
  #smoking_variables <- smoking %>% select(seqn,smq020,smq040)
  #smoking_variables <- smoking_variables %>% filter(smq020 == 1 | smq020 == 2)
  
  #### nas are nos for smoking 
  #smoking_variables$smq040[is.na(smoking_variables$smq040)] <- 0
  
  #### dumming out smoking 
  #smoking_variables$smq040 <- ifelse(smoking_variables$smq040 == 0, 0, ifelse(smoking_variables$smq040 == 1, 1, ifelse(smoking_variables$smq040 == 2, 1, ifelse(smoking_variables$smq040 == 3,0, ifelse(smoking_variables$smq040 == 7,NA,NA)))))

#### IV: Hypertension Medication
hypertension_variables <- hypertension %>% select(seqn,bpq020,bpq040a)
  #### only yes and nos 
  hypertension_variables <- hypertension_variables %>% filter(bpq020 == 1 | bpq020 == 2)
  hypertension_variables$bpq020[hypertension_variables$bpq020 == 2] <- 0
  
  #### nas are nos for hypertension 
  hypertension_variables$bpq040a[is.na(hypertension_variables$bpq040a)] <- 0
  
  #### dumming out hypertension
  hypertension_variables$bpq040a <- ifelse(hypertension_variables$bpq040a == 0, 0, ifelse(hypertension_variables$bpq040a == 1, 1, ifelse(hypertension_variables$bpq040a == 2, 0, ifelse(hypertension_variables$bpq040a == 7,NA, ifelse(hypertension_variables$smq040 == 9,NA,NA)))))

####IV: glucose 
glu_variables <- glucose %>% select(seqn,lbxglu)

####merge 
lin_frame <- dv_bp 
variables <- c("bmi_variables","demo_variables","dia_variables","bad_chol_variables","chol_variables","glu_variables","hypertension_variables")
for(i in 1:length(variables))
{
  lin_frame <- merge(lin_frame,eval(as.name(variables[i])),by=c("seqn"))
}
summary(lin_frame)

## 75% of the sample size
smp_size <- floor(0.75 * nrow(lin_frame))

## set the seed to make your partition reproducible
#set.seed(123)
train_ind <- sample(seq_len(nrow(lin_frame)), size = smp_size)

lin_frame <- lin_frame[train_ind, ]
lin_frame_test <- lin_frame[-train_ind, ]

```

```{r}
#### test frame 
lin_frame_test$bmxrecum <- NULL 
lin_frame_test <- subset(lin_frame_test, select=-c(seqn,bpxsy1,bpxsy2,bpxsy3,bpxdi1,bpxdi2,bpxdi3)) 
lin_frame_test <- na.omit(lin_frame_test)
lin_frame_test$id <- seq.int(nrow(lin_frame_test))
####Prediction Frame 
lin_frame$bmxrecum <- NULL 
lin_frame_clean <- subset(lin_frame, select=-c(seqn,bpxsy1,bpxsy2,bpxsy3,bpxdi1,bpxdi2,bpxdi3)) 
lin_frame_clean <- na.omit(lin_frame_clean)



#### Blood Pressure Frame 
lin_frame_bp <- na.omit(lin_frame)
summary(lin_frame_bp)


```