---
title: "linear_model"
output: html_document
editor_options: 
chunk_output_type: console
---
PRIMARY PURPOSE: 
The purpose of this .Rmd is to build a linear model for both systolic and diastolic blood pressure to establish a reasonable baseline for the study. 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(readr)
library(matrixStats)
library(reshape2)
library(car)
library(MASS)
```






```{r}
lin_frame_clean %>% ggplot(aes(dia_mean,sys_mean)) + geom_point()
```


```{r}
#### Systolic prediction 
#### correlation
sys_lin <- subset(lin_frame_clean, select=-c(dia_mean,ridreth3,mult))

#### model 1: linear regression
bpsys_linear1 = lm(sys_mean~.,sys_lin)
summary(bpsys_linear1)

  #### looking at variance explained by interactions
  bpsys_interact = lm(sys_mean~(.)^2,sys_lin)
  anova(bpsys_interact)

  #### residual assumption 
  #### overal residual values 
  plot(bpsys_linear1$fitted.values,bpsys_linear1$residuals)
  
  #### all residuals 
  crPlots(bpsys_linear1)

  
  #### qq-plot
  qqPlot(bpsys_linear1,ylab="Standardized Residuals", xlab="Normal Scores")
  
  #### correcting bmxsad1
  res_correct = lm(sys_mean~log(bmxsad1),sys_lin)
  res_not = lm(sys_mean~(bmxsad1),sys_lin)
  crPlots(res_not)
  crPlots(res_correct)
  
  #### correcting bmxwt
  res_correct = lm(sys_mean~log(bmxwt),sys_lin)
  res_not = lm(sys_mean~(bmxwt),sys_lin)
  crPlots(res_not)
  crPlots(res_correct)
  
  
  #### correcting year 
  res_correct = lm(sys_mean~I(ridageyr^2),sys_lin)
  res_not = lm(sys_mean~(ridageyr),sys_lin)
  crPlots(res_not)
  crPlots(res_correct)
  
  ####correcting lbdldl
  res_correct = lm(sys_mean~log(lbdldl),sys_lin)
  res_not = lm(sys_mean~(lbdldl),sys_lin)
  crPlots(res_not)
  crPlots(res_correct)

  
  ####correcting lbxtc
  res_correct = lm(sys_mean~log(lbxtc),sys_lin)
  res_not = lm(sys_mean~(lbxtc),sys_lin)
  crPlots(res_not)
  crPlots(res_correct)
  
  ####correcting lbxglu
  res_correct = lm(sys_mean~log(lbxglu),sys_lin)
  res_not = lm(sys_mean~(lbxglu),sys_lin)
  crPlots(res_not)
  crPlots(res_correct)

#### model 2: linear regression
bpsys_linear2 = lm(sys_mean~ bmxarmc + bmxsad1 + bmxht + bmxwaist + bmxwt + riagendr + ridageyr + I(ridageyr^2) + hispanic + white + black + diq010 + lbdldl + log(lbxtc) + log(lbxglu) + bpq020 + bpq040a + bmxarmc:ridageyr + riagendr:lbdldl + riagendr:lbxglu + bmxsad1:diq010 + riagendr:ridageyr + bmxsad1:bpq040a  + ridageyr:white + ridageyr:diq010 + ridageyr:lbdldl  , sys_lin)
summary(bpsys_linear2)

export_summs(bpsys_linear2, scale = TRUE)
write.csv(table1, "model1.csv")

####keep in original for interaction and transformation 
  #### residual assumption 
  #### overal residual values 
  plot(bpsys_linear2$fitted.values,bpsys_linear2$residuals)
  
  #### all residuals 
  crPlots(bpsys_linear2)

  
  #### qq-plot
  qqPlot(bpsys_linear2,ylab="Standardized Residuals", xlab="Normal Scores")



#### prediction 
sys_predictions = predict(bpsys_linear2, newdata = lin_frame_test)
summary(sys_predictions)
summary(lin_frame_test$sys_mean)

### MSE data frame 
mse <- data.frame(id = seq.int(nrow(lin_frame_test)), true_sys = lin_frame_test$sys_mean, true_dia = lin_frame_test$dia_mean, sys_lin_mse = (lin_frame_test$sys_mean - sys_predictions)^2, sys_lin = sys_predictions) 

```

```{r}
#### Diastolic prediction 
#### correlation
dia_lin <- subset(lin_frame_clean, select=-c(sys_mean,ridreth3,mult))
cor(dia_lin)


#### model 1: linear regression
bpdia_linear1 = lm(dia_mean~.,dia_lin)
summary(bpdia_linear1)

  #### looking at variance explained by interactions
  bpsys_interact = lm(dia_mean~(.)^2,dia_lin)
  anova(bpsys_interact)

  #### residual assumption 
  #### overal residual values 
  plot(bpdia_linear1$fitted.values,bpdia_linear1$residuals)
  
  #### all residuals 
  crPlots(bpdia_linear1)

  
  #### qq-plot
  qqPlot(bpdia_linear1,ylab="Standardized Residuals", xlab="Normal Scores")
  
  #### correcting lbdldl
  res_correct = lm(sys_mean~log(lbdldl),sys_lin)
  res_not = lm(sys_mean~(lbdldl),sys_lin)
  crPlots(res_not)
  crPlots(res_correct)
  
  #### correcting lbxglu
  res_correct = lm(sys_mean~log(lbxglu),sys_lin)
  res_not = lm(sys_mean~(lbxglu),sys_lin)
  crPlots(res_not)
  crPlots(res_correct)
  
  #### correcting lbxtc
  res_correct = lm(sys_mean~log(lbxtc),sys_lin)
  res_not = lm(sys_mean~(lbxtc),sys_lin)
  crPlots(res_not)
  crPlots(res_correct)
  
  #### correcting bmxwt
  res_correct = lm(sys_mean~log(bmxwt),sys_lin)
  res_not = lm(sys_mean~(bmxwt),sys_lin)
  crPlots(res_not)
  crPlots(res_correct)
  
  #### correcting bmxbmi
  res_correct = lm(sys_mean~log(bmxbmi),sys_lin)
  res_not = lm(sys_mean~(bmxbmi),sys_lin)
  crPlots(res_not)
  crPlots(res_correct)

#### model 2: linear regression
bpdia_linear2 = lm(dia_mean~ bmxarmc + bmxsad1 + log(bmxwt) + riagendr + ridageyr + I(ridageyr^2) + white + black + asian + diq010 + log(lbdldl) + lbxtc + bpq020 + bpq040a + ridageyr:white +  bmxsad1:ridageyr + ridageyr:bpq040a + riagendr:lbdldl,dia_lin)
summary(bpdia_linear2)

table1 <- export_summs(bpsys_linear2,bpdia_linear2, scale = TRUE)
write.csv(table1, "model2.csv")
  #### residual assumption 
  #### overal residual values 
  plot(bpdia_linear2$fitted.values,bpdia_linear2$residuals)
  
  #### all residuals 
  crPlots(bpdia_linear2)

  
  #### qq-plot
  qqPlot(bpdia_linear2,ylab="Standardized Residuals", xlab="Normal Scores")

#### prediction 
dia_predictions = predict(bpdia_linear2, newdata = lin_frame_test)
summary(dia_predictions)
summary(lin_frame_test$dia_mean)

#### MSE Frame update
mse$dia_lin_mse <- (lin_frame_test$dia_mean - dia_predictions)^2
mse$dia_lin  <- dia_predictions
mal_pred <- cbind(mse$dia_lin,mse$sys_lin)
mal_true <- cbind(mse$true_dia,mse$true_sys)
mse$lin_mal <- mahalanobis(mal_pred, mal_true, cov(mal_pred,mal_true))


```



```{r}
### Density frame and plot for dia 
  ### Frame Creation 
  density_dia <- mse %>% select(predicted_dia,true_dia,first_dia)
  density_dia <- melt(density_dia)
  
  ### Plot 
  ggplot(density_dia, aes(x=value, fill=variable)) +
    geom_density(alpha=0.4)
  
  
### MSE frame and plot for dia
  bar_dia <- mse %>% select(sys_lin_mse, dia_lin_mse) %>% summarise(predict_sys_mse = mean(sys_lin_mse), predict_dia_mse = mean(dia_lin_mse))
  bar_dia <- melt(bar_dia)
  bar_dia[,1] <- as.character(bar_dia[,1])
  bar_dia[1,1] <- "Systolic Blood Pressure"
  bar_dia[2,1] <- "Diastolic Blood Pressure"
  bar_dia[,1] <- as.factor(bar_dia[,1])
  ggplot(bar_dia, aes(x=variable, y=value, fill = variable)) +
  geom_bar(stat="identity") + theme_minimal() + labs(title="MSE of Linear Regression Prediction for Systolic and Diastolic Blood Pressure", 
   x="Blood Pressure", y="Mean Squared Error")
  
```

```{r}
### Density frame and plot for sys
  ### Frame Creation 
  density_sys <- mse %>% select(predicted_sys,true_sys,first_sys)
  density_sys <- melt(density_sys)
  
  ### Plot 
  ggplot(density_sys, aes(x=value, fill=variable)) +
    geom_density(alpha=0.4)

### MSE frame and plot for sys 
  bar_sys <- mse %>% select(first_sys_mse, predict_sys_mse) %>% summarise(first_sys_mse = mean(first_sys_mse), predict_sys_mse = mean(predict_sys_mse))
  bar_sys <- melt(bar_sys)
  
  ggplot(bar_sys, aes(x=variable, y=value, fill = variable)) +
  geom_bar(stat="identity") + theme_minimal() 

  
  
### NEED TO THROW OUT DIASTOLIC OBSERVATION 
### CHECK FOR OUTLIERS AFTER CORRECTION 
### SCATTER PLOT FIRST vs. TRUE 
### DIASTOLIC HAS A QUADRATIC TREND WITH AGE 
### PREDICITNG BLOOD PRESSURE TRAJECTORY USING CLUSTERING 
### Histogram of differences 
ggplot(mse, aes(true_dia,dia_lin))+
    geom_point() + geom_abline(aes(intercept=0, slope=1, col = "slope = 1")) + geom_smooth(method="lm")  + labs( 
   x="Predicted Diastolic", y="True Diastolic") + theme_minimal() 
summary(lm(true_dia~dia_lin,mse))

ggplot(mse, aes(true_sys,sys_lin))+
    geom_point() + geom_abline(aes(intercept=0, slope=1, col = "slope = 1")) + geom_smooth(method="lm") + labs( 
   x="Predicted Systolic", y="True Systolic") + theme_minimal()


ggplot(mse_try, aes(true_dia,rf_dia_pred))+
    geom_point() + geom_abline(aes(intercept=0, slope=1, col = "slope = 1")) + geom_smooth(method="lm")  + labs( 
   x="Predicted Diastolic", y="True Diastolic") + theme_minimal()
summary(lm(true_dia~dia_lin,mse))

ggplot(mse_try, aes(true_sys,rf_sys_pred))+
    geom_point() + geom_abline(aes(intercept=0, slope=1, col = "slope = 1")) + geom_smooth(method="lm") + labs( 
   x="Predicted Systolic", y="True Systolic") + theme_minimal() 

summary(lm(true_sys~rf_sys_pred, mse_try))
summary(lm(true_dia~rf_dia_pred, mse_try))
vara <- lin_frame_clean
vara$ridageyr[vara$ridageyr>=90 & vara$ridageyr<=99] <- 9
vara$ridageyr[vara$ridageyr>=80 & vara$ridageyr<=89] <- 8
vara$ridageyr[vara$ridageyr>=70 & vara$ridageyr<=79] <- 7
vara$ridageyr[vara$ridageyr>=60 & vara$ridageyr<=69] <- 6
vara$ridageyr[vara$ridageyr>=50 & vara$ridageyr<=59] <- 5
vara$ridageyr[vara$ridageyr>=40 & vara$ridageyr<=49] <- 4
vara$ridageyr[vara$ridageyr>=30 & vara$ridageyr<=39] <- 3
vara$ridageyr[vara$ridageyr>=20 & vara$ridageyr<=29] <- 2
vara$ridageyr[vara$ridageyr>=10 & vara$ridageyr<=19] <- 1
ggplot(vara, aes(x=as.factor(ridageyr),y=sys_mean)) + geom_boxplot() + theme_minimal() + labs(x = "age in decades",y= "Systolic Mean") 

ggplot(vara, aes(x=as.factor(ridageyr),y=dia_mean)) + geom_boxplot() + theme_minimal() + labs(x = "age in decades",y= "Diastolict Mean") 
```

