---
title: "random forest"
output: html_document
editor_options: 
chunk_output_type: console
---

PRIMARY PURPOSE: 
The purpose of this .Rmd is to build a random forest model for both systolic and diastolic blood pressure to compare to the linear baseline. The mse data frame created in the linear_model.Rmd is updated with the decision trees performance. As a result running linear_model.Rmd is necessary for this file to function properly. 



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(caret) 
library(ggplot2)
library(dplyr)
library(readr)
library(Hmisc)
library(ggfortify)
library(rpart.plot)
library(reshape2)

knitr::opts_knit$set(root.dir = normalizePath("C:/Users/buehl/Documents/classes/senior-research"))
```


```{r}
#___________________________________________________________________________________________________
#### CONSTRUCTING RANDOM FOREST for systolic blood pressure on each of the clusters 
#___________________________________________________________________________________________________

####building the model
sys_tree <- subset(lin_frame_clean, select=-c(dia_mean,ridreth3,mult))
trctrl = trainControl(method = "repeatedcv", number = 10, repeats = 3)
tunegrid = expand.grid(mtry=c(1:2)) ###tuning parameter
rf_sys_tree = train(sys_mean~., 
                               data = sys_tree, method = "rf", 
                               parms = list(split = "information"), 
                               trControl=trctrl,ntrees = 1000,tuneGrid = tunegrid,importance=TRUE)
plot(rf_sys_tree)
rf_sys_tree$results

#evaluate variable importance
varImp(rf_sys_tree, scale = FALSE)
sys_imp <- as.data.frame(varImp(rf_sys_tree, scale = FALSE)$importance)
sys_imp$X1 <- rownames(sys_imp)
### prediction 
rf_sys_pred <- predict(rf_sys_tree, newdata = lin_frame_test)

### MSE data frame 
mse$rf_pred_sys <- rf_sys_pred

mse$rf_sys_mse <- (mse$true_sys - mse$rf_pred_sys)^2
```

```{r}
#___________________________________________________________________________________________________
#### PLOTTING VARIABLE PERFORMANCE for SYSTOLIC 
#___________________________________________________________________________________________________
sys_plot <- sys_imp[order(sys_imp[,1]),][11:21,]
ggplot(sys_imp, aes(y=Overall, x=reorder(X1,Overall),fill="red")) + 
  geom_bar(stat = "summary") + 
  coord_flip()  + 
  theme_minimal() + 
  scale_fill_discrete(guide=FALSE) + 
  scale_x_discrete(labels=c("Asian","Hispanic","White","LDL Chol.","HDL Chol.","Diabetes","Cholesterol","Black","Leg Circum.","Lower Arm Circum.","Gender","Glucose","Abdomin Circum.","Upper Arm Circum.", "Height","BMI","Hypertension Med.","Waist Circum.","Weight","Hypertension","Age")) +   labs(x="Predictor", y="Importance to Systolic Pressure") +
  theme(axis.text=element_text(size=20), axis.title=element_text(size=20)) 
```


```{r}
#___________________________________________________________________________________________________
#### CONSTRUCTING RANDOM FOREST for diastolic blood pressure on each of the clusters 
#___________________________________________________________________________________________________
####building the model 
dia_tree <- subset(lin_frame_clean, select=-c(sys_mean,ridreth3,mult))
trctrl = trainControl(method = "repeatedcv", number = 10, repeats = 3)
tunegrid = expand.grid(mtry=c(1:2)) ###tuning parameter
rf_dia_tree = train(dia_mean~., 
                               data = dia_tree, method = "rf", 
                               parms = list(split = "information"), 
                               trControl=trctrl,ntrees = 1000,tuneGrid = tunegrid,importance = TRUE)
plot(rf_dia_tree)
rf_dia_tree$results

#Evaluate variable importance
varImp(rf_dia_tree, scale = FALSE)
dia_imp <- as.data.frame(varImp(rf_dia_tree, scale = FALSE)$importance)
dia_imp$X1 <- rownames(sys_imp)

### prediction 
rf_dia_pred <- predict(rf_dia_tree, newdata = lin_frame_test)

### MSE data frame 
mse$rf_pred_dia <- rf_dia_pred

mse$rf_dia_mse <- (mse$true_dia - mse$rf_pred_dia)^2

### malahonbis distance 
mal_pred <- cbind(mse$rf_pred_dia,mse$rf_pred_sys)
mal_true <- cbind(mse$true_dia,mse$true_sys)
mse$rf_mal <- mahalanobis(mal_pred, mal_true, cov(mal_pred,mal_true))
```


```{r}
#___________________________________________________________________________________________________
#### PLOTTING VARIABLE PERFORMANCE for SYSTOLIC 
#___________________________________________________________________________________________________
dia_plot <- dia_imp[order(dia_imp[,1]),][11:21,]

ggplot(dia_imp, aes(y=Overall, x=reorder(X1,Overall),fill="red")) + geom_bar(stat = "summary") + coord_flip()  + theme_minimal() + scale_fill_discrete(guide=FALSE) + scale_x_discrete(labels=c("Black","Hispanic","White","HDL Chol.","Glucose","Diabetes","Gender","Hypertension Med.", "Asian","Leg Circum.","Lower Arm Circum.", "Hypertension","LDL Chol.","Height","Abdomin Circum.","Upper Arm Circum.","Cholesterol","BMI","Weight","Waist Circum.","Age")) + labs( 
   x="Predictor", y="Importance to Diastolic Pressure") +
  theme(axis.text=element_text(size=20), axis.title=element_text(size=20)) 


```

```{r}
#___________________________________________________________________________________________________
#### COMPARING PREDICTED VALEUS TO ACTUAL VALUES FROM LINEAR MODELS 
#___________________________________________________________________________________________________
ggplot(mse, aes(true_dia,dia_lin))+
  geom_point() + 
  geom_abline(aes(intercept=0, slope=1, col = "slope = 1")) + 
  geom_smooth(method="lm",aes(col = "Fitted Line")) +
  labs(x="Predicted Diastolic", y="True Diastolic") + 
  theme_minimal() +
  theme(axis.text=element_text(size=20), axis.title=element_text(size=20,face="bold"),legend.text=element_text(size=20)) 

ggplot(mse, aes(true_sys,sys_lin))+
  geom_point() + 
  geom_abline(aes(intercept=0, slope=1, col = "slope = 1")) + 
  geom_smooth(method="lm",aes(col = "Fitted Line")) +
  labs(x="Predicted Systolic", y="True Systolic") + 
  theme_minimal() +
  theme(axis.text=element_text(size=20), axis.title=element_text(size=20,face="bold"),legend.text=element_text(size=20)) 

summary(lm(true_dia~rf_pred_dia,mse))
summary(lm(true_sys~rf_pred_sys,mse))
```

```{r}
#___________________________________________________________________________________________________
#### Saving Finalized Models 
#___________________________________________________________________________________________________

###age, wasit circum, 
save(rf_dia_tree , file = 'RandomForestDia.rda')
save(rf_sys_tree , file = 'RandomForestSys.rda')
write.csv(mse,"mse.csv")
```

