---
title: "variance_BP"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(readr)
library(Hmisc)
library(matrixStats)

```


```{r}
#selecting blood pressure columns 
bp <- bloodpressure.XPT
bp_columns <- grep("bpxsy[1-3]|bpxdi[1-3]", names(bp), ignore.case=T)
bp <- bp[,bp_columns]

#dropping NAs 
bp <- na.omit(bp)

#filtering zero values
row_sub = apply(bp, 1, function(row) all(row !=0 ))
bp <- bp[row_sub,]

#calculating mean column 
bp$dia_mean <- rowMeans(bp[,c(2,4,6)])
bp$sys_mean <- rowMeans(bp[,c(1,3,5)])


```

```{r}
#Looking at variance 
cov(bp)

#correlation
cor(bp$dia_mean,bp$sys_mean)

#looking at relation between diastolic and systolic 
ggplot(bp, aes(x=dia_mean, y=sys_mean)) +
    geom_point(shape=1) 

```
```{r}
#within person variance
bp$within_sys_var <- apply(bp[,c(1,3,5)],1,var)
bp$within_dia_var <- apply(bp[,c(2,4,6)],1,var)
#mean 
bp$mean_within_sys_var <- mean(bp$within_sys_var)
bp$mean_within_dia_var <- mean(bp$within_dia_var)

#between variance
cor(bp[,c(1,3,5,8)])
cor(bp[,c(2,4,6,7)])

```



